# Generated by Django 3.2.7 on 2021-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=96)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=96)),
                ('address', models.CharField(max_length=500)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('wallet_balance', models.IntegerField()),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
