# Generated by Django 4.1.1 on 2022-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid_number', models.CharField(max_length=100)),
                ('Department_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Services', models.CharField(max_length=300)),
                ('Start_date', models.DateField()),
                ('Start_time', models.CharField(max_length=100)),
                ('End_date', models.DateField()),
                ('End_time', models.CharField(max_length=100)),
                ('PdfLink', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Particiaped', models.BooleanField(default=False)),
            ],
        ),
    ]
