# Generated by Django 4.1.1 on 2022-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Services', models.CharField(max_length=1000)),
                ('Locations', models.CharField(max_length=1000)),
            ],
        ),
    ]
